### PR TITLE
33 get all categories

### LINKED ISSUE #33: GET /categories <Route>
* Description:
  - [x] Get all categories from database then send it to client side
  - [x] Test all units

* Response:
  * Success (200):
    ```js
    {
      message: 'Success',
      data:  {
        categories: ["", "", ....]
      }
    }
    ```
  * Failed (400):
    ```js
    {
      message: 'There is no categories',
    };
    ```

### PR DESCRIPTION
**Pull request by ghost**
closes #33

### CODE REVIEW

File: server/controllers/categories/getAllCategories.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+import { CustomedError } from '../../utils';
+
+const getAllCategories = async (
+  req: Request,
+  res: Response,
+  next: NextFunction,
+) => {
+  try {
+    const categories: any = await Category.findAll({
+      attributes: ['id', 'name', 'icon_url'],
```
Comment (Raghad-Mezied) [inline server/controllers/categories/getAllCategories.ts:12]: I think these are all the attributes in the categories table, right? . If yes then you dont need to specified the attributes

File: server/tests/route.test.ts [hunk 2]
```diff
@@ -157,16 +155,26 @@ describe('POST/signUp', () => {
...
+      .expect(
+        'set-cookie',
+        'ACCESS_TOKEN=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT',
+      );
     expect(response.body.message).toBe('logged out successfully!');
   });
 });
 
+describe('GET/categories', () => {
+  test('get all categories from database', async () => {
```
Comment (Raghad-Mezied) [inline server/tests/route.test.ts:172]: What about the other cases

**Review by Raghad-Mezied — CHANGES_REQUESTED** [review]

**Review by haniolwan — APPROVED** [review]

**Review by Raghad-Mezied — APPROVED** [review]

**Review by DinaAlghazali — APPROVED** [review]

**Review by farah2003 — APPROVED** [review]
