### PR TITLE
97 get contact

### LINKED ISSUE #97: GET /api/admin/reports?page=<number>
## Description:
  - [x] Get all reports from database then send it to client side
  - [x] Test all units

* Response:
  * Success (200):
    ```js
    {
      message: 'Success',
      data:  {
        reports: ["", "", ....],   // => <10 reports in page>
        count: <number of all reports>
      }
    }
    ```
  * Failed (400):
    ```js
    {
      message: <Validation error message>,
    };
    ```

### PR DESCRIPTION
**Pull request by ghost**
closes #97

### CODE REVIEW

File: server/controllers/reportsRouter/getReports.ts [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+import { Contact } from '../../database/models';
+
+const getReports = async (req: Request, res: Response, next: NextFunction) => {
+  try {
+    const reports = await Contact.findAll({
+      attributes: {
+        exclude: ['createdAt', 'updatedAt'],
+      },
+    });
+    res.json({ message: 'Success', data: { reports } });
```
Comment (Raghad-Mezied) [inline server/controllers/reportsRouter/getReports.ts:11]: You need to send the reports depending on the page.
And rename the Contact model to Report so we have the same name in all files.

**Review by Raghad-Mezied — CHANGES_REQUESTED** [review]

File: server/controllers/reports/getReports.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
+import { Request, Response, NextFunction } from 'express';
+import { Report } from '../../database/models';
+
+const getReports = async (req: Request, res: Response, next: NextFunction) => {
+  try {
+    const { page = 1, limit = 10 }: any = req.query;
```
Comment (Raghad-Mezied) [inline server/controllers/reports/getReports.ts:6]: Validate the query before.

**Review by Raghad-Mezied — CHANGES_REQUESTED** [review]

**Review by farah2003 — APPROVED** [review]

**Review by Raghad-Mezied — APPROVED** [review]

**Review by DinaAlghazali — APPROVED** [review]

**Review by haniolwan — APPROVED** [review]
