### PR TITLE
107 delete family

### LINKED ISSUE #107: DELETE /api/admin/family/id
* Description:
  - [x] Delete family by id => id will come from param
  - [x] Test all units

* Response:
  * Success (200):
    ```js
    {
      message: 'Family deleted successfully',
    }
    ```
  * Failed (400):
    ```js
    {
      message: "The family you are trying to delete doesn't exist",
    }
    ```

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

File: server/controllers/families/deleteFamilyById.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+  try {
+    const deletedFamily = await Family.destroy({
+      where: {
+        id,
+      },
+    });
+    if (!deletedFamily) {
+      res.status(400).json({
+        message: "The family you are trying to delete doesn't exist",
+      });
```
Comment (Raghad-Mezied) [inline server/controllers/families/deleteFamilyById.ts:19]: Why do you handle the error response here? throw the error so the server error will handle it.

File: server/controllers/families/deleteFamilyById.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
+import { Request, Response, NextFunction } from 'express';
+import { Family } from '../../database/models';
+
+const deleteFamilyById = async (
+  req: Request,
+  res: Response,
+  next: NextFunction,
+) => {
+  const { id } = req.params;
```
Comment (Raghad-Mezied) [inline server/controllers/families/deleteFamilyById.ts:9]: Validate the param first

**Review by Raghad-Mezied — CHANGES_REQUESTED** [review]

**Review by Raghad-Mezied — APPROVED** [review]

**Review by DinaAlghazali — APPROVED** [review]

**Review by farah2003 — APPROVED** [review]

**Review by haniolwan — APPROVED** [review]
