### PR TITLE
POST /login

### LINKED ISSUE #8: POST /login <Route>
* Description:
  - [x] Create Login Schema
  - [x] Validate Inputs
  - [x] Get User by his Email from Database
  - [x] Compare Entered Password with Password in Database 
  - [x] If there is Validation with User Give him Access_Token (signAuth)
  - [x] Assign cookie with Access_Token
  - [x] Handle Errors
* Request body:
```js
{
  email: 'email@gmail.com',
  password: 'your password'
}
```
* Validation:
```js
{
  email: string()
    .max(250)
    .min(4)
    .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } })
    .required(),
  password: string().max(50).min(3).required(),
}
```

* Response:
  * Success (200):
    ```js
    { 
      message: 'Successfully logged in',
      data:  {
        id: 'user id',
        name: 'username',
        isAdmin: 'true or false',
      }
     }
    ```
  * Failed (400):
    ```js
    {
      message: "Email doesn't exists, Try another one or sign up",
    };
    ```
    ```js
    {
      message: "Incorrect password, please try again",
    };
    ```

### PR DESCRIPTION
**Pull request by ghost**
Relates #8
Closes #8

### CODE REVIEW

File: server/utils/loginSchema.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+
+const loginSchema = Joi.object({
+  email: Joi.string()
+    .max(250)
+    .min(4)
+    .email({ minDomainSegments: 2, tlds: { allow: ['com', 'net'] } })
+    .required(),
+  password: Joi.string().max(50).min(3).required(),
+});
+export default loginSchema;
```
Comment (Raghad-Mezied) [inline server/utils/loginSchema.ts:11]: Add a separated folder called validation, and `index` file and import from it

File: server/controllers/auth/login.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+    }
+    const payload = {
+      id: user?.getDataValue('id'),
+      name: user?.getDataValue('name'),
+      isAdmin: user?.getDataValue('is_admin'),
+    };
+    const token = jwt.sign(payload, process.env.SECRET as string, {
+      expiresIn: '30d',
+      algorithm: 'HS256',
+    });
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:42]: You are using sign sync, so convert it to promise and use is asyc.

File: server/controllers/auth/login.ts [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+    if (!user) {
+      throw new CustomedError(
+        "Email doesn't exists, Try another one or sign up",
+        406,
+      );
+    }
+    const isPasswordValidate = await bcrypt.compare(
+      password,
+      user?.getDataValue('password'),
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:29]: You already check the user above, right?

File: server/controllers/auth/login.ts [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+    );
+    if (!isPasswordValidate) {
+      throw new CustomedError('Incorrect password, please try again', 406);
+    }
+    const payload = {
+      id: user?.getDataValue('id'),
+      name: user?.getDataValue('name'),
+      isAdmin: user?.getDataValue('is_admin'),
+    };
+    const token = jwt.sign(payload, process.env.SECRET as string, {
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:39]: destructure the sign.

**Review by Raghad-Mezied — CHANGES_REQUESTED** [review]

**Review by farah2003 — APPROVED** [review]

File: server/controllers/auth/login.ts [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+            algorithm: 'HS256',
+          },
+          (err, encoded) => {
+            if (err) reject(err);
+            else resolve(encoded);
+          },
+        ),
+      );
+    });
+    res
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:52]: converted it to promise in another file, and then use it here

File: server/controllers/auth/login.ts [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+      .status(200)
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:53]: Its the default so you don't need to send it

File: server/controllers/auth/login.ts [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+
+    const user = await Donor.findOne({
+      where: {
+        email,
+      },
+    });
+    if (!user) {
+      throw new CustomedError(
+        "Email doesn't exists, Try another one or sign up",
+        406,
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:21]: 406? I don't think this is right

File: server/controllers/auth/login.ts [hunk 8]
```diff
@@ -0,0 +1,65 @@
...
+      );
+    }
+    const isPasswordValidate = await bcrypt.compare(
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:24]: Destructure the compare

File: server/controllers/auth/login.ts [hunk 9]
```diff
@@ -0,0 +1,65 @@
+import { NextFunction, Request, Response } from 'express';
+import bcrypt from 'bcryptjs';
+import jwt from 'jsonwebtoken';
+import loginSchema from '../../utils/loginSchema';
+import CustomedError from '../../utils/customedError';
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:5]: you can import them in one line

**Review by Raghad-Mezied — CHANGES_REQUESTED** [review]

File: server/controllers/auth/login.ts [hunk 10]
```diff
@@ -0,0 +1,52 @@
...
+      throw new CustomedError('Unexpected Error', 500);
+    }
+    res
+      .cookie('ACCESS_TOKEN', token, {
+        maxAge: 900000,
+        httpOnly: true,
+      })
+      .json({ message: 'Successfully logged in', data: payload });
+  } catch (error) {
+    if (error.details) next(new CustomedError(error.details[0].message, 400));
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:47]: Maybe it's more proper to check the name of the error.

File: server/controllers/auth/login.ts [hunk 11]
```diff
@@ -0,0 +1,52 @@
...
+
+    const payload = {
+      id: user?.getDataValue('id'),
+      name: user?.getDataValue('name'),
+      isAdmin: user?.getDataValue('is_admin'),
+    };
+    const token = await signToken(payload);
+    if (typeof token !== 'string') {
+      throw new CustomedError('Unexpected Error', 500);
+    }
```
Comment (Raghad-Mezied) [inline server/controllers/auth/login.ts:39]: Why did you need to add this condition?

File: jest.config.ts [hunk 12]
```diff
@@ -0,0 +1,9 @@
+import type { Config } from '@jest/types';
+// Sync object
+const config: Config.InitialOptions = {
+  verbose: true,
+  transform: {
+    '^.+\\.(ts)?$': 'ts-jest',
+  },
+};
+export default config;
```
Comment (Raghad-Mezied) [inline jest.config.ts:9]: Add a comment to your teammates with a brief explanation of these things that may need explanation, or you can add it to the issue description.

**Review by Raghad-Mezied — CHANGES_REQUESTED** [review]

File: server/controllers/auth/login.ts (hunk 11 above)
Comment (Mohammed-Hamada) [reply server/controllers/auth/login.ts:39]: Because if there is error when sign token, this condition will throw it

File: server/controllers/auth/login.ts (hunk 10 above)
Comment (Mohammed-Hamada) [reply server/controllers/auth/login.ts:47]: `Joi` return an object with validation error and it contains `details` property, so here i check if this property exists, then i throw an error.

File: jest.config.ts (hunk 12 above)
Comment (Mohammed-Hamada) [reply jest.config.ts]: Repaired.

File: server/controllers/auth/login.ts (hunk 10 above)
Comment (Raghad-Mezied) [reply server/controllers/auth/login.ts:47]: Your right, but I am not sure if there are other errors that contain the property.

File: server/controllers/auth/login.ts (hunk 11 above)
Comment (Raghad-Mezied) [reply server/controllers/auth/login.ts:39]: But if there is an error then it will be catched in the catch.

Comment (Mohammed-Hamada) [reply server/controllers/auth/login.ts]: Yes, that's more efficient than handle error by another property.

Comment (Mohammed-Hamada) [reply server/controllers/auth/login.ts]: Repaired.

File: server/controllers/auth/login.ts (hunk 10 above)
Comment (Mohammed-Hamada) [reply server/controllers/auth/login.ts]: Yes, that's more efficient than handle error by another property.

Comment (Mohammed-Hamada) [reply server/controllers/auth/login.ts]: Repaired.

File: server/controllers/auth/login.ts (hunk 11 above)
Comment (Mohammed-Hamada) [reply server/controllers/auth/login.ts]: Yes, it will caught automatically.

**Review by DinaAlghazali — APPROVED** [review]

**Review by haniolwan — APPROVED** [review]

File: server/tests/route.test.ts [hunk 13]
```diff
@@ -0,0 +1,122 @@
...
+      .post('/api/login')
+      .send({
+        email: 'admin@gmail.com',
+        password: '123456789',
+      })
+      .expect(200);
+    expect(
+      response.headers['set-cookie'][0].startsWith('ACCESS_TOKEN'),
+    ).toEqual(true);
+  });
```
Comment (Raghad-Mezied) [inline server/tests/route.test.ts:49]: This is not a new case to test, you should test it with the previous two tests. if they set a cookie or not.

**Review by Raghad-Mezied — CHANGES_REQUESTED** [review]

File: server/tests/route.test.ts (hunk 13 above)
Comment (Mohammed-Hamada) [reply server/tests/route.test.ts]: Repaired.

**Review by Raghad-Mezied — APPROVED** [review]
