### PR TITLE
111 get campaigns

### LINKED ISSUE #111: GET /api/admin/campaigns?page=<number>
## Description:
  - [ ] Get all campaigns from database then send it to client side
  - [ ] Test all units

* Response:
  * Success (200):
    ```js
    {
      message: 'Success',
      data:  {
        campaigns: ["", "", ....],   // => <15 campaign in page>
        count: <number of all campaigns>
      }
    }
    ```
  * Failed (400):
    ```js
    {
      message: <Validation error message>,
    };
    ```

### PR DESCRIPTION
**Pull request by ghost**
closes #111

### CODE REVIEW

**Review by farah2003 — APPROVED** [review]

**Review by haniolwan — APPROVED** [review]

File: server/controllers/campaigns/getCampaigns.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+import { CustomError, querySchema } from '../../utils';
+
+const getCampaigns = async (
+  req: Request,
+  res: Response,
+  next: NextFunction,
+) => {
+  try {
+    const { page = 1 }: any = req.query;
+    await querySchema.validateAsync(req.query);
```
Comment (HaniOlwan) [inline server/controllers/campaigns/getCampaigns.ts:12]: const { page = 1 }:any = await querySchema.validateAsync(req.query);

**Review by Raghad-Mezied — APPROVED** [review]

**Review by DinaAlghazali — APPROVED** [review]

**Review by haniolwan — APPROVED** [review]
